services:
  nginx:
    image: nginx:latest
    container_name: nginx_bx24
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /run/media/iboss/udata/dev/php:/var/www/html
      - ./certs:/etc/nginx/ssl
      - ./kafka_certs:/etc/nginx/ssl/kafka_abs/
    depends_on:
      - php
    networks:
      bx24_network:
        aliases:
          - b24.doc
          - bxapps.doc
          - "*.java.loc"

  php:
    build: .
    container_name: php_bx24
    volumes:
      - /run/media/iboss/udata/dev/php:/var/www/html
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./certs:/usr/local/share/ca-certificates/
      - ./kafka_certs:/etc/nginx/ssl/kafka_abs/
    networks:
      - bx24_network

  java:
    image: eclipse-temurin:21-jre
    container_name: java_bx24
    working_dir: /apps
    volumes:
      - /run/media/iboss/udata/dev/java:/apps
      - ./java-runner.sh:/usr/local/bin/java-runner.sh
    command: [ "/bin/bash", "/usr/local/bin/java-runner.sh" ]
    environment:
      - JAVA_OPTS=-Xmx256m -Xms128m
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=bitrix
      - DB_PASSWORD=1234
    ports:
      - "8080-8099:8080-8099"
    depends_on:
      - mariadb
    networks:
      - bx24_network
    restart: unless-stopped

  # тот же mysql
  mariadb:
    image: mariadb:11.7
    container_name: mariadb_bx24
    environment:
      MARIADB_ROOT_PASSWORD: 123456
      MARIADB_DATABASE: sitemanager
      MARIADB_USER: bitrix
      MARIADB_PASSWORD: 1234
    user: "952:952"  # Указать UID и GID из команды 'id mysql' с локального компа!
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - /var/lib/mysql:/var/lib/mysql
    ulimits:
      nofile:
        soft: 128000
        hard: 128000
    networks:
      - bx24_network

networks:
  bx24_network:
    driver: bridge