services:
  nginx:
    image: nginx:latest
    container_name: nginx_bx24
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /run/media/iboss/udata/dev/php/bx24.loc:/var/www/html
      - ./certs:/etc/nginx/ssl
    depends_on:
      - php
    networks:
      - bx24_network

  php:
    build: .
    container_name: php_bx24
    volumes:
      - /run/media/iboss/udata/dev/php/bx24.loc:/var/www/html
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - bx24_network

  # тот же mysql
  mariadb:
    image: mariadb:11.5
    container_name: mariadb_bx24
    environment:
      MARIADB_ROOT_PASSWORD: 123456
      MARIADB_DATABASE: sitemanager
      MARIADB_USER: bitrix
      MARIADB_PASSWORD: 1234
    user: "952:952"  # Указать UID и GID из команды 'id mysql' с локального компа!
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - /var/lib/mysql:/var/lib/mysql
    ulimits:
      nofile:
        soft: 128000
        hard: 128000
    networks:
      - bx24_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: no
    links:
      - mariadb:db
    ports:
      - 8765:83
    environment:
      MYSQL_ROOT: 'root'
      MYSQL_ROOT_PASSWORD: '0000'
      MYSQL_USER: 'bitrix'
      MYSQL_PASS: '1234'
      UPLOAD_LIMIT: 300M
    depends_on:
      - mariadb
    networks:
      - bx24_network
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - /var/lib/mysql:/var/lib/mysql

networks:
  bx24_network:
    name: bx24_network
